import 'antd/dist/antd.css';
import './Button'
import './Input'
import './SignIn'
import './SignUp'
import './Segment'
import './ProfileImage';
import './PostSection';
import './CapsuleButton';
import './CheckBox';
import './TimelineCover';
import './TimelineHeader';